### ISSUE TITLE
Pulling an image INFO message is misleading

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/dunner#112]
**Describe the bug**
`INFO[2019-07-19 23:39:20] Pulling an image: 'golang'` This message is misleading when the system already has the Docker image pulled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a `.dunner.yaml`
2. Add a task
3. Run the task ( This will pull the image )
4. Run the task again

**Expected behaviour**
Dunner should not pull the image again nor show an INFO message saying pulling image.

**Screenshots**
![Screenshot from 2019-07-19 23-42-52](https://user-images.githubusercontent.com/1391468/61556296-0f8d5580-aa7f-11e9-96dc-96653433cf71.png)

**Comment by ayushjn20** [comment]
Closed with reference to #121
