### ISSUE TITLE
Locally built images not recognized 

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/dunner#114]
**Bug**
Dunner can not recognize the locally built Docker images

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a `.dunner.yaml`
2. Ad a task which refers to a locally built Docker image rather a hosted one in a repo
3. Run the task

**Expected behaviour**
Dunner should pick the local Docker image and run the commands on it.

**Screenshots**
![Screenshot from 2019-07-20 11-23-24](https://user-images.githubusercontent.com/1391468/61574741-5ca21380-aae1-11e9-9cab-c1da4bcbcbf8.png)

**Comment by ayushjn20** [comment]
Closed with reference to #121
