### ISSUE TITLE
Integrate a unit testing framework and add tests

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/Dunner#18]
We need to have unit tests to cover all the units of Dunner

**Comment by ayushjn20** [comment]
Hey @agentmilindu, I am working on a patch that will cover the following,
* Restructure and refactoring according to community standards.[ #5 ]
* Add unit test files for services.[ #18 ]
* Add `.travis.yml` for automated testing using Travis CI. [ #13 ]

**Comment by agentmilindu** [comment]
Nice, but don't make PRs huge. Good if your can break the patch into smaller chunks and send small PRs quickly.
It's makes development quick. I'm waiting till you push the refactoring things to proceed with they rest of my work, because unless it would make lot of conflicts.

**Comment by ayushjn20** [comment]
@agentmilindu Issue can be closed with reference to #21 .

**Comment by agentmilindu** [comment]
Fixed with #21
