### ISSUE TITLE
Add command to check for syntax/lint errors in '.dunner.yaml'

### ISSUE THREAD

**Issue by ayushjn20** [leopardslab/dunner#31]
Currently only a single command exists: `do`. Let's say that someone wants to only check for a valid dunner file, then there is no option except to run all the commands using `do`. 

Although it is easy to write the dunner file, it would be great if we could add a new command as syntax validator that can point some of the errors if present without actually running the dunner file.

An alternate solution could be to add support of flag `--check-lint` in the `do` command itself, but I recommend a separate command considering the future potential and complexity of this tool.

**Comment by agentmilindu** [comment]
What I have seen with AWS CLI and several others is, they have an option called `--dry-run`. We can follow the same.  WDYT?

CC @rehrumesh @charithccmc @rhperera @rajikaimal

**Comment by apoorvam** [comment]
`dunner do --dry-run` seems good as its a dry run of just `do`. 

However, the title of this issue seems similar to #55 (dunner validate) ?

**Comment by agentmilindu** [comment]
@apoorvam yes, I divided this task into two different tasks. I forgot to mention it here.

CC @ayushjn20

**Comment by apoorvam** [comment]
We now have `dunner validate` as well as dry run option. So this issue is not valid. Closing for now.
