### ISSUE TITLE
Brew formula for Dunner

### ISSUE THREAD

**Issue by apoorvam** [leopardslab/Dunner#49]
I'm adding a `brew` formula for Dunner, as it's a go-to package manager for Mac OS. I have started to create a PR on this, but brew needs a URL link to project source tarball. Usually, its referenced from GitHub releases. However, I see no releases made for Dunner so far. 

Is it possible to make an initial release for this repository?

**Comment by agentmilindu** [comment]
Yeah, that's cool! 
I just merged version `v1.0.0` of Dunner! Let me create a release now.

**Comment by agentmilindu** [comment]
@apoorvam https://github.com/leopardslab/Dunner/tree/v1.0.0

**Comment by apoorvam** [comment]
Awesome! 
I have raised a PR to homebrew to include `dunner`. Will wait for this PR to get merged: https://github.com/Homebrew/homebrew-core/pull/37916 @agentmilindu

**Comment by apoorvam** [comment]
Homebrew needs a repository to pass criteria of one of these: 
`<30 forks, <30 watchers and <75 stars`
Once this limit is passed, PR can get merged.

**Comment by agentmilindu** [comment]
@apoorvam Shall we try to create a personal tap as he has suggested? We can then use it for testing with Mac OS until we get listed in Brew

**Comment by apoorvam** [comment]
@agentmilindu I have created a brew tap in my repository:  Can you fork it to `leopardslab` profile?
https://github.com/apoorvam/homebrew-dunner

After that `brew install leopardslab/homebrew-dunner/dunner` or `brew tap leopardslab/dunner` should install dunner.

**Comment by agentmilindu** [comment]
Done https://github.com/leopardslab/homebrew-dunner
Nicejob @apoorvam!

**Comment by apoorvam** [comment]
@agentmilindu Can add below instructions in Installation Guide wiki:

```
# 2. Install via Homebrew

Dunner can be installed via Homebrew. On Mac OS X, you can install by running below command:

```
brew tap leopardslab/dunner
```
or
```
brew install leopardslab/homebrew-dunner/dunner
```

To reinstall, run `brew reinstall dunner`.
```

I could not send PR to that due to access issues.

**Comment by apoorvam** [comment]
@agentmilindu Please make above changes to wiki, so we can close this issue for now.
