### ISSUE TITLE
Dunner Dry Run

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/dunner#56]
`Dunner do somecommand --dry-run` will pull the images fro Docker hub but will not run the commands, just like dry run in other applications.

**Comment by agentmilindu** [comment]
@ayushjn20 I broke down #31 into two tasks

**Comment by ayushjn20** [comment]
I guess not just pulling of image from Docker hub, but all other stuff like mounting directories except running the commands should be included.
Shall I proceed like this?

**Comment by agentmilindu** [comment]
agree, yes, proceed

**Comment by ayushjn20** [comment]
Closed with reference to #65
