### ISSUE TITLE
Integrate a logging lib

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/Dunner#7]
Integrate and configure a good logging library for logging purposes.

https://github.com/op/go-logging seems good.

**Comment by championballer** [comment]
@agentmilindu Can I be assigned this issue?

**Comment by agentmilindu** [comment]
Yeah, please proceed with this and send a PR

**Comment by championballer** [comment]
@agentmilindu If this is done, do you think it would be better to close this?  Do you plan to have anything else added with reference to this issue?

**Comment by agentmilindu** [comment]
Let's close this!
