### ISSUE TITLE
Ability to use env variables in mount directory source

### ISSUE THREAD

**Issue by apoorvam** [leopardslab/dunner#85]
In the `mounts` config of dunner, we cannot use environment variables. 
Eg:
```
    mounts:
      - "`$BUILD_DIR`:/root/pics:wr"

```
Above gives error in config.

### Expected
Dunner config should allow use of env for source and dest dir in mount directory.

**Comment by apoorvam** [comment]
Creating a separate issue for ability to use relative path as it should be applicable in multiple options, not just mount dir.

**Comment by agentmilindu** [comment]
Fixed by #88
