### ISSUE TITLE
Build a Deb Package

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/dunner#9]
Dunner should be packaged and distributed as a Deb package

**Comment by gane5hvarma** [comment]
@agentmilindu would like to work on this.is anyone workng on this?

**Comment by agentmilindu** [comment]
@gane5hvarma Please proceed

**Comment by agentmilindu** [comment]
@ayushjn20 You are working on this, right? How's the progress?

**Comment by ayushjn20** [comment]
Facing some errors regarding system dependencies. Might take longer time than expected.

**Comment by apoorvam** [comment]
Have started releasing deb packages from release v2.1.1. Deb install instructions are added here: https://github.com/leopardslab/dunner/wiki/Installation-Guide
